package configs;

import java.util.HashMap;
import java.util.Map;

public class RndConf {
    public static final int MIN_WIDTH_MOBILE = 360;
    public static final int MAX_HEIGHT_MOBILE = 800;
    public static final int MIN_WIDTH_LARGE = 1920;
    public static final int MAX_HEIGHT_LARGE = 1080;
    public static final Long MIN_PROTEINS = 1L;
    public static final Long MAX_PROTEINS = 1000L;
    public static final Long MIN_FAT = 1L;
    public static final Long MAX_FAT = 1500L;
    public static final Long MIN_CARBS = 1L;
    public static final Long MAX_CARBS = 100L;
    public static final Long MIN_CALORIES = 1L;
    public static final Long MAX_CALORIES = 2500L;
    public static final Long MIN_PRICE = 1L;
    public static final Long MAX_PRICE = 20000L;
    public static final String[] INGREDIENT_TYPES = {"FILLING", "TOPPING", "SAUCE", "SPICE"};
    public static final String INGREDIENT_FLUORESCENT_BUN_HASH = "61c0c5a71d1f82001bdaaa6d";
    public static final String INGREDIENT_CARDBOARD_BUN_HASH = "61c0c5a71d1f82001bdaaa6c";
    public static final String INGREDIENT_SPICY_X_SAUCE_HASH = "61c0c5a71d1f82001bdaaa72";
    public static final String INGREDIENT_SPACE_SAUCE_HASH = "61c0c5a71d1f82001bdaaa73";
    public static final String INGREDIENT_TRADITIONAL_GALACTIC_SAUCE_HASH = "61c0c5a71d1f82001bdaaa74";
    public static final String INGREDIENT_ANTARIAN_FLATBREAD_SPIKES_SAUCE_HASH = "61c0c5a71d1f82001bdaaa75";
    public static final String INGREDIENT_PROTOSTOMIA_IMMORTALIS_MEAT_HASH = "61c0c5a71d1f82001bdaaa6f";
    public static final String INGREDIENT_BEEF_METEORITE_CHOP_HASH = "61c0c5a71d1f82001bdaaa70";
    public static final String INGREDIENT_MARTIAN_MAGNOLIA_BIOCOAT_HASH = "61c0c5a71d1f82001bdaaa71";
    public static final String INGREDIENT_LUMINESCENT_TETRAODONTIMEFORM_FILLET_HASH = "61c0c5a71d1f82001bdaaa6e";
    public static final String NGREDIENT_CRUNCHY_MINERAL_RINGS_FILLET_HASH = "61c0c5a71d1f82001bdaaa76";
    public static final String INGREDIENT_FRUITS_FALLENIAN_HASH = "61c0c5a71d1f82001bdaaa77";
    public static final String INGREDIENT_MARTIAN_ALPHA_SACCHARIDES_CRYSTALS_HASH = "61c0c5a71d1f82001bdaaa78";
    public static final String INGREDIENT_EXO_PLANTAGO_SALAD = "61c0c5a71d1f82001bdaaa79";
    public static final String INGREDIENT_CHEESE_WITH_ASTEROID_MOLD = "61c0c5a71d1f82001bdaaa7a";
    public static final Map<String, String> INGREDIENTS = new HashMap<>();

    static {
        INGREDIENTS.put("FLUORESCENT_BUN", INGREDIENT_FLUORESCENT_BUN_HASH);
        INGREDIENTS.put("CARDBOARD_BUN", INGREDIENT_CARDBOARD_BUN_HASH);
        INGREDIENTS.put("SPICY_X_SAUCE", INGREDIENT_SPICY_X_SAUCE_HASH);
        INGREDIENTS.put("SPACE_SAUCE", INGREDIENT_SPACE_SAUCE_HASH);
        INGREDIENTS.put("TRADITIONAL_GALACTIC_SAUCE", INGREDIENT_TRADITIONAL_GALACTIC_SAUCE_HASH);
        INGREDIENTS.put("ANTARIAN_FLATBREAD_SPIKES_SAUCE", INGREDIENT_ANTARIAN_FLATBREAD_SPIKES_SAUCE_HASH);
        INGREDIENTS.put("PROTOSTOMIA_IMMORTALIS_MEAT", INGREDIENT_PROTOSTOMIA_IMMORTALIS_MEAT_HASH);
        INGREDIENTS.put("BEEF_METEORITE_CHOP", INGREDIENT_BEEF_METEORITE_CHOP_HASH);
        INGREDIENTS.put("MARTIAN_MAGNOLIA_BIOCOAT", INGREDIENT_MARTIAN_MAGNOLIA_BIOCOAT_HASH);
        INGREDIENTS.put("LUMINESCENT_TETRAODONTIMEFORM_FILLET", INGREDIENT_LUMINESCENT_TETRAODONTIMEFORM_FILLET_HASH);
        INGREDIENTS.put("CRUNCHY_MINERAL_RINGS_FILLET", NGREDIENT_CRUNCHY_MINERAL_RINGS_FILLET_HASH);
        INGREDIENTS.put("FRUITS_FALLENIAN", INGREDIENT_FRUITS_FALLENIAN_HASH);
        INGREDIENTS.put("MARTIAN_ALPHA_SACCHARIDES_CRYSTALS", INGREDIENT_MARTIAN_ALPHA_SACCHARIDES_CRYSTALS_HASH);
        INGREDIENTS.put("EXO_PLANTAGO_SALAD", INGREDIENT_EXO_PLANTAGO_SALAD);
        INGREDIENTS.put("CHEESE_WITH_ASTEROID_MOLD", INGREDIENT_CHEESE_WITH_ASTEROID_MOLD);
    }
}
